using './main.bicep'

param location = 'eastus'
param resourceGroupName = 'rg-bc-shop-placeholder'
param webAppName = 'bc-shop-web-placeholder'
param functionAppName = 'bc-shop-functions-placeholder'
param atlasApiKey = ''
param atlasCampaignIdPt = ''
param atlasCampaignIdEn = ''
param atlasBaseUrl = 'https://api.youratlas.com/v1/api'
param bcAgentApiKey = ''
param atlasWebhookSecret = ''
